version: '3'
services:
  tp-foyer:
    image: firasrebai/tp-foyer:1.0.0
    ports:
      - "8089:8089"
    networks:
      - app-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge